version: "3.8"

services:
  backend:
    build: .
    container_name: sugarsense_backend
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/sugarsense
    volumes:
      - .:/app

  mongo:
    image: mongo:latest
    container_name: sugarsense_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
